name: dart_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
   watcher: ^1.0.0


dev_dependencies:
  build_runner:
  lints: ^2.0.0
  test: ^1.21.0
