name: dart_demo
description: Demo application
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
   watcher: ^1.0.0


dev_dependencies:
  build_runner:
  lints: ^2.0.0
  test: ^1.21.0
